print(f"Twinkle, twinkle, little star,")
print(f"\tHow I wonder what you are!")
print(f"\t\tUp above the world so high,")
print(f"\t\tLike a diamond in the sky.")
print(f"Twinkle, twinkle, little star,")
print(f"\tHow I wonder what you are!")